# Generated by Django 3.1.6 on 2021-04-01 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luminarApp', '0021_auto_20210401_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('2', 'Admitted'), ('1', 'Call back'), ('3', 'Cancel')], max_length=20),
        ),
        migrations.CreateModel(
            name='EnquiryThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiryId', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=50)),
                ('collegename', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enquirydate', models.DateField(default=datetime.date(2021, 4, 1))),
                ('followup_date', models.DateField()),
                ('status', models.CharField(choices=[('2', 'Admitted'), ('1', 'Call back'), ('3', 'Cancel')], max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luminarApp.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luminarApp.course')),
            ],
        ),
    ]
