# Generated by Django 3.1.6 on 2021-04-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarApp', '0023_auto_20210401_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('1', 'Call back'), ('3', 'Cancel'), ('2', 'Admitted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enquirythree',
            name='status',
            field=models.CharField(choices=[('1', 'Call back'), ('3', 'Cancel'), ('2', 'Admitted')], max_length=20),
        ),
    ]
