# Generated by Django 3.1.6 on 2021-05-14 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarApp', '0034_auto_20210513_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=150)),
                ('total_fees', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 14)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_date',
            field=models.DateField(default=datetime.date(2021, 5, 14)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('2', 'Ongoing'), ('1', 'Yet to Begin'), ('3', 'Completed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquirydate',
            field=models.DateField(default=datetime.date(2021, 5, 14)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('3', 'Cancel'), ('1', 'Call back'), ('2', 'Admitted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enquirythree',
            name='enquirydate',
            field=models.DateField(default=datetime.date(2021, 5, 14)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date(2021, 5, 14)),
        ),
    ]
