# Generated by Django 3.1.6 on 2021-05-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarApp', '0035_auto_20210514_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('2', 'Ongoing'), ('3', 'Completed'), ('1', 'Yet to Begin')], max_length=30),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('2', 'Admitted'), ('1', 'Call back'), ('3', 'Cancel')], max_length=20),
        ),
    ]
