# Generated by Django 3.1.6 on 2021-05-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarApp', '0036_auto_20210514_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('3', 'Completed'), ('2', 'Ongoing'), ('1', 'Yet to Begin')], max_length=30),
        ),
        migrations.AlterField(
            model_name='enquirythree',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
