# Generated by Django 3.1.6 on 2021-05-17 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarApp', '0038_auto_20210514_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 17)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_date',
            field=models.DateField(default=datetime.date(2021, 5, 17)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('1', 'Yet to Begin'), ('3', 'Completed'), ('2', 'Ongoing')], max_length=30),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquirydate',
            field=models.DateField(default=datetime.date(2021, 5, 17)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Admitted', '2'), ('Call back', '1'), ('Cancel', '3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enquirythree',
            name='enquirydate',
            field=models.DateField(default=datetime.date(2021, 5, 17)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date(2021, 5, 17)),
        ),
    ]
