# Generated by Django 3.1.6 on 2021-05-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luminarApp', '0047_auto_20210517_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('3', 'Cancel'), ('1', 'Call back'), ('2', 'Admitted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='admission_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luminarApp.admission'),
        ),
    ]
