# Generated by Django 3.1.6 on 2021-05-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luminarApp', '0050_auto_20210517_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='admission_nos',
            new_name='admission_no',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='admission_nos',
            new_name='admission_no',
        ),
    ]
