# Generated by Django 3.1.6 on 2021-05-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminarApp', '0051_auto_20210517_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('3', 'Cancel'), ('1', 'Call back'), ('2', 'Admitted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='admission_no',
            field=models.CharField(max_length=50),
        ),
    ]
