# Generated by Django 3.1.6 on 2021-05-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luminarApp', '0056_auto_20210517_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admissions',
        ),
    ]
