# Generated by Django 3.1.6 on 2021-05-18 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luminarApp', '0060_auto_20210517_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 18)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_date',
            field=models.DateField(default=datetime.date(2021, 5, 18)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquirydate',
            field=models.DateField(default=datetime.date(2021, 5, 18)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('3', 'Cancel'), ('2', 'Admitted'), ('1', 'Call back')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enquirythree',
            name='enquirydate',
            field=models.DateField(default=datetime.date(2021, 5, 18)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date(2021, 5, 18)),
        ),
        migrations.CreateModel(
            name='AdmissionNewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=50, unique=True)),
                ('coursefees', models.IntegerField()),
                ('date', models.DateField(default=datetime.date(2021, 5, 18))),
                ('batchcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luminarApp.batch')),
                ('enquiryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luminarApp.enquirythree')),
            ],
        ),
    ]
