# Generated by Django 3.1.6 on 2021-05-18 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luminarApp', '0064_auto_20210518_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('3', 'Cancel'), ('1', 'Call back'), ('2', 'Admitted')], max_length=20),
        ),
        migrations.CreateModel(
            name='BatchModelNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('batch_date', models.DateField(default=datetime.date(2021, 5, 18))),
                ('course_fees', models.CharField(max_length=50)),
                ('batch_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luminarApp.batchstatus')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luminarApp.course')),
            ],
        ),
    ]
